### ISSUE TITLE
track source selections on mobile

### ISSUE THREAD

**Issue by katebrune** [scott-street/moodqueue#51]
**Current Behavior**
on moodqueue-stage rn, the track source selections aren't aligned on page load. when i click an option, they align and are the right size. not sure what is up with this.

**Intended Behavior**
the track source selections are aligned

![IMG_981CA4FA8E14-1](https://user-images.githubusercontent.com/31379789/95413546-55874100-08f1-11eb-92b9-38d641299323.jpeg)

**Comment by lorenzoz23** [comment]
well seeing as this was found on a previous version of stage and the fact that i do have aligned sources showing on my phone, i think this could be resolved. maybe check again with the updated stage and see? also remember to add that shit to home screen so it looks all the coooler

**Comment by katebrune** [comment]
just checked current stage & it's resolved, good catch, imma close this
