### ISSUE TITLE
our transparency to free-tier spotify users

### ISSUE THREAD

**Issue by lorenzoz23** [scott-street/moodqueue#82]
i'm making this issue because i realized, as a free-tier spotify user, there is nothing in the app to tell me why the hell i can't build queues. i would be questioning the purpose and validity of an app called moodqueue if my only option is to create a playlist and there's no info button anywhere telling me why.

should we always include the queue button but disable it for free users? 
or should we make a lil user details modal that pops up when a user clicks their avatar and that tells them what kind of spotify user they are and how that relates to moodqueue. we could also put their link to their profile in the modal to make it less unnecessary and more settings-like.

**Comment by katebrune** [comment]
what if after they log in, if they're a free user we pop up a lil info modal thats like "hey heres whats up" and have an okay button that makes the modal disappear and then we just disable the queue button for free users?

**Comment by lorenzoz23** [comment]
yeah, that's certainly an idea and i could see it working but i'm definitely gonna ask jess about this because i have no idea what the right thing to do in this situation would be.

**Comment by lorenzoz23** [comment]
jess said we should keep the queue button there but disable it and add a tool tip so that when users hover over, it will explain why they can't click it. with mobile, since we can't hover there, we can possibly have the queue button enabled but display a tooltip when a free user clicks on it.

https://wwayne.github.io/react-tooltip/

**Comment by katebrune** [comment]
that's smart, love it

does grommet not have a tooltip?
